export const ROUTERS = {
  HOME: "/",
  PRODUCT: "/product",
  PRODUCT_CREATE: "/product/create",
  PRODUCT_EDIT: "/product/edit/:id",
  PRODUCT_DETAIL: "/product/detail/:id",
  CATEGORY: "/category",
  BRAND: "/brand",
  MODEL: "/model",
  VARIANT_TYPE: "/variant-type",
  VARIANT_VALUE: "/variant-value",
  PURCHASE: "/purchase",
  PURCHASE_CREATE: "/purchase/create",
  PURCHASE_EDIT: "/purchase/edit/:id",
  PURCHASE_DETAIL: "/purchase/detail/:id",
  PURCHASE_INVOICE: "/purchase/invoice/:id",
  PURCHASE_PAYMENT: "/purchase-payment",
  STORE: "/store",
  STORE_CREATE: "/store/create",
  STORE_EDIT: "/store/edit/:id",
  STOCK: "/stock",
  SUPPLIER: "/supplier",
  CUSTOMER: "/customer",
  SALE: "/sale",
  SALE_CREATE: "/sale/create",
  SALE_EDIT: "/sale/edit/:id",
  SALE_DETAIL: "/sale/detail/:id",
  SALE_INVOICE: "/sale/invoice/:id",
  SALE_COMPLETE: "/sale/complete/:id",
  PAYMENT: "/payment",
  SALES: "/sales",
  BANK: "/bank",
  CURRENCY: "/currency",
  ROLE: "/role",
  PERMISSION: "/permission",
  GROUP_PERMISSION: "/group-permission",
  USER: "/user",
  REPORT: "/report",
  REPORT_SALES: "/report/sales",
  REPORT_SALES_ITEMS: "/report/sales-items",
  REPORT_EXPENSES: "/report/expenses",
  REPORT_PRODUCT_SERIALS: "/report/product-serials",
  CHANGE_PASSWORD: "/change-password",
  LOGIN: "/login",
  REGISTER: "/register",
  FORGOT_PASSWORD: "/forgot-password",
  DASHBOARD: "/",
  ROLE_PERMISSIONS: "/permission",
  FILE_UPLOAD: "/file-upload",
  CUSTOMERS: "/customers",
  PROFILE: "/profile",

  EXPENSE_TYPE: "/expense-type",
  EXPENSE: "/expense",
  QUOTE: "/quote",
};

export const AUTHENTICATION = {
  REFRESH_TOKEN: "refreshToken",
};