name: Telegram Notification

on:
  push:
    branches:
      - '**'

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram Message
        uses: appleboy/telegram-action@master
        with:
          to: "-1003966601591"
          token: "8008593219:AAHKG0hNi8pM-kR-g9mUOB631qiHZuByfjY"
          message_thread_id: "3"
          format: markdown 
          message: |
            📦 **New Push Event**
            📂 **Repository:** ${{ github.repository }}
            🌿 **Branch:** `${{ github.ref_name }}`
            👤 **Committer:** ${{ github.actor }}
            💬 **Message:** ${{ github.event.head_commit.message }}
            🔗 **Commit URL:** ${{ github.event.head_commit.url }}